### ISSUE TITLE
How to get optional claims?

### ISSUE THREAD

**Issue by shashankkr** [06chaynes/okta-jwt-verifier#1]
Hi,
I am creating a custom HTTP gateway/router 
clients -> router -> backend/s
that needs to 

1. verify the jwt token issued by OKTA
2. the client can have 1 or many optional claims which are not pre defined. I need to parse them and add them as the HTTP Headers before routing the request to the correct backend, so that the backends can implement the RBAC rules 

1 is straightforward but any suggestion on how can I implement 2?

Thanks in advance.

**Comment by 06chaynes** [comment]
You can provide your own claims struct, I just provide a default struct that tries to cover the basic use cases but it's not required. You could start with the default, provided below:
```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct DefaultClaims {
    pub iss: String,
    pub sub: String,
    pub scp: Option<Vec<String>>,
    pub cid: Option<String>,
    pub uid: Option<String>,
    pub exp: u64,
    pub iat: u64,
}
```

Then tweak it to suit your needs:
```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct MyCustomClaims {
    pub iss: String,
    pub sub: String,
    pub scp: Option<Vec<String>>,
    pub cid: Option<String>,
    pub uid: Option<String>,
    pub exp: u64,
    pub iat: u64,
    pub myoptfield: Option<String>
}
```

Does that help any?

**Comment by shashankkr** [comment]
Hi @06chaynes, thanks for replying. Not really and I am sorry I didnt explain my problem in detail. So this is the token the router might receive 
```
{
  "ver": 1,
  "jti": "AT.ukSRTP4gHAhHvW38Np0dd15Ec1_VFaFiu2UPJEwa43o",
  "iss": "https://company.okta.com/oauth2/aus1r4telqpwk3xYT0h8",
  "aud": "api://default",
  "iat": 1675789141,
  "exp": 1675790041,
  "cid": "0oa1r4too1swbZMqK0h8",
  "scp": [
    "graphql"
  ],
  "sub": "0oa1r4too1swbZMqK0h8",
  "custom_claim1": "reader",
  "custom_claim2": "writer",
   ......
   "custom_claimN:"some_role"
}
```

These custom claims are not predefined and depends on the client and the scope. So I was thinking that decode the token as a hasmap, iterate on the keys, remove all default claims keys, whatever is left in the hashmap will be these custom claims. 
This decoding and coverting the token to a hasmap is where I am stuck :). Or if you have a better solution to do this then please let me know. 
Again, thanks for the help!!!

**Comment by 06chaynes** [comment]
Ah I see, well not really sure but I think this would be more of a serde thing. You might be able to implement your own deserializer: https://serde.rs/deserialize-map.html

Some more related links to check:
https://github.com/serde-rs/serde/issues/1387
https://users.rust-lang.org/t/serde-deserialize-struct-with-dynamically-prefixed-fields/22258/2
https://serde.rs/enum-representations.html

**Comment by shashankkr** [comment]
Thanks for providing the links.
